2025-06-27 01:18:22,150 - app - WARNING - [fetch_stock_data] No data returned for SBIN.NS
2025-06-27 01:18:31,005 - app - WARNING - [fetch_stock_data] No data returned for AXISBANK.NS
2025-06-27 01:18:35,204 - app - WARNING - [fetch_stock_data] No data returned for ITC.NS
2025-06-27 01:19:39,109 - app - WARNING - [fetch_stock_data] No data returned for ITC.NS
2025-06-27 01:24:38,158 - app - WARNING - [fetch_stock_data] No data returned for AXISBANK.NS
2025-06-27 01:24:58,903 - app - WARNING - [fetch_stock_data] No data returned for ITC.NS
2025-06-27 09:38:58,170 - app - WARNING - [fetch_stock_data] No data returned for SBIN.NS
2025-06-27 15:20:07,459 - app - WARNING - [fetch_stock_data] No data returned for ITC.NS
2025-06-27 15:44:28,109 - app - WARNING - [fetch_stock_data] No data returned for INFY.NS
2025-06-27 16:08:45,461 - app - WARNING - [fetch_stock_data] No data returned for SBIN.NS
2025-06-27 16:08:58,275 - app - WARNING - [fetch_stock_data] No data returned for SBIN.NS
2025-06-27 19:16:45,085 - app - WARNING - [fetch_stock_data] No data returned for SBIN.NS
2025-06-27 21:18:08,873 - app - WARNING - [fetch_stock_data] No data returned for AXISBANK.NS
2025-06-27 21:21:18,640 - app - WARNING - [fetch_stock_data] No data returned for AXISBANK.NS
2025-06-27 21:21:51,421 - app - WARNING - [fetch_stock_data] No data returned for HINDUNILVR.NS
2025-06-27 21:21:54,013 - app - WARNING - [fetch_stock_data] No data returned for HINDUNILVR.NS
2025-06-28 15:44:44,890 - app - ERROR - Exception on /about [GET]
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 680, in about
    return render_template('about.html')
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: about.html
